package com.planning.nacleica.WebInteractionService;

public enum WebServiceActions {
    AUTHENTIFICATION,
    GETNEWWORKERTASKS,
    GETPROGRESSWORKERTASKS,
    GETDONEWORKERTASKS,
    GETNEWADMINTASKS,
    GETADMINMAKETTASKS,
    GETWORKERS,
    ADDWORKERS,
    UPDATEWORKER,
    ASSIGNTASK,
    UPDATETASK,
    GETWORKER,
    GETSTATUSTASKSWORKERS,
    CREATENEWTASK

}
